# The Kubernetes Cluster where the resources wil be created
# Defaults to local cluster where ArgoCD is deployed
destination:
  server: https://kubernetes.default.svc
# The Git server to used by the application
source:
  # the source repository on git
  repoURL:
  # The branch/tag to use for the source repo
  targetRevision: main
sigstore:
  policyController:
    version: 0.3.9
argocd:
  imageUpdater:
    image:
      tag: 0.12.2
    version: 0.8.2
    logLevel: info
    registries: []
helloWorld:
  deploy: false
  image:
    repo: ""
